### ISSUE TITLE
Anwenden der DIN 461 auf lediglich eine Achse

### ISSUE THREAD

**Issue by Lowrider614** [OlliK94/matlab-din461#2]
Hallo OlliK94,
die DIN461 sieht zwar nicht vor, dass nur eine Achse entsprechend formatiert ist. Bei Balkendiagrammen die auf der Ordinate beispielweise eine Spannung in MPa anzeigen, wäre das aber sinnvoll. Auf der Abszisse steht dann die Bedeutung der einzelnen Balken, da wäre die Anwendung der DIN nicht sinnvoll.
Anbei ein pdf wo das schon mal umgesetzt ist. Ich habe dazu einfach alle Teile des Codes die mit der x Achse zu tun hatten auskommentiert. Allerdings auch den resize listener. 

Schöne Grüße

Tim

**Comment by OlliK94** [comment]
Hallo Tim,
ich habe die Funktionen xdin461 und ydin461 hinzugefügt, mit denen man die DIN461 nur auf einer Achse anwenden kann. Allerdings muss man beachten, dass dann auch nur auf der einen Achse die Dezimalpunkte durch Kommas ersetzt werden.

Schöne Grüße

Oliver

**Comment by Lowrider614** [comment]
Super, vielen Dank! Funktioniert prima.
